### ISSUE TITLE
Parse Error on some special characters such as <>

### ISSUE THREAD

**Issue by Den-dp** [sapics/html-minifier-loader#3]
Hi! Looks like `html-minifier-loader` (or its internals) breaks on html like this

``` html
<span>User name contains bad characters like: !$&*()|?/<>\'`"%</span>
```

```
Module build failed: Error: Parse Error: <>\'`"%</span>
```

I know about `&lt;` and `&amp;` but to my knowledge the code above is valid.

And my question is where should I address with this problem?

Thanks

**Comment by ShimShamSam** [comment]
This issue is with [kangax/html-minifier](https://github.com/kangax/html-minifier). This repo is only a loader to enable it for Webpack. The bug (which is dubious since you should be using &lt;) may already be fixed in kangax/html-minifier, but this loader is using v1 of it, the latest being v3. There's currently a pull request pending that would allow you to install any version of kangax/html-minifier with this loader which may solve the issue.

**Comment by sapics** [comment]
Thanks @ShimShamSam for help!

**Comment by sapics** [comment]
I guess that current version v1.2.0 would fix your problem. Please try it.
